### ISSUE TITLE
The importer doesn't handle all data in 3dm files yet

### ISSUE THREAD

**Issue by dahuaigou** [jesterKing/import_3dm#131]
![image](https://github.com/user-attachments/assets/5a8a74d9-b48f-40d8-ba67-63612586772f)blender4.2.3 Error at installation

**Comment by dahuaigou** [comment]
![image](https://github.com/user-attachments/assets/0e15d255-f2a4-4dfc-84c4-ed1160c4929f)

**Comment by jesterKing** [comment]
The first warning is not an error. It is mentioned by the add-on itself so that users know not to expect a full import of a 3dm file.

The message that there is no module `rhino3dm` means you need to restart Blender after installing the add-on.

This is explained in the installation instructions as well.

**Comment by dahuaigou** [comment]
But I have restarted it and still reported the error

**Comment by dahuaigou** [comment]
![image](https://github.com/user-attachments/assets/3913d140-0fd3-4588-8c3f-cc9a6d9e09cb)
There was a problem with the folder structure, and the sub-folder RHINO3DM could not be recognized, causing the plug-in to report an error

**Comment by jesterKing** [comment]
After restarting also re-enable the add-on.
