### ISSUE TITLE
can't find this addon under user preferences

### ISSUE THREAD

**Issue by retsyo** [jesterKing/import_3dm#2]
I am using official blender 2.79 64bits for win64. After install the import_3dm addon, I can't find it under `blender user preferences` -> `add-ons`

I found this from `system console`
```
fake_module: addon missing 'bl_info' gives bad performance!: 'E:\\greensoft\\3d\\blender\\blender-2.79-windows64\\2.79\\scripts\\addons\\import_3dm.py'
```

PS. I know how to install python package and blender addons

**Comment by jesterKing** [comment]
The current code is for Blender 2.80. Furthermore the script isn't a full add-on yet. Rather you'll have to load it in the text editor, then run it from that.

I hope to get a better add-on format done in the coming time, so that you can actually install it as an add-on.

I'm not sure if I'm going to adapt the code for 2.79.

**Comment by jesterKing** [comment]
Once PR #1 is in this issue will be fixed.
